services:
  - type: web
    name: loconuts-wordpress
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: WORDPRESS_ENV
        value: production
      - key: WP_DEBUG
        value: false
      - key: DB_NAME
        value: wordpress
      - key: DB_USER
        value: wordpress_user
      # NOTE: DB_PASSWORD and DB_HOST must be set manually in Render dashboard
      # after MySQL service is created, or they will be auto-provided by Render
    routes:
      - path: /
        matchType: prefix
    healthCheckPath: /

databases:
  - name: wordpress_db
    engine: mysql
    version: "8.0"
    plan: starter
    region: ohio
    databaseName: wordpress
    user: wordpress_user